name: dry-run

on:
  push

jobs:
  jsr:
    name: publish-to-jsr
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Publish to JSR
        run: deno publish --dry-run
